### ISSUE TITLE
资源占用优化

### ISSUE THREAD

**Issue by jzm1241** [WangXuan95/Hard-PNG#1]
你好 在嘛，可以聊一下关于hard-png的修改问题嘛。针对于已知8位灰度png图的解码是否可以优化下资源占用呢，目前资源占用较大，芯片资源不足以支撑原有的代码。还有就是目前需要图像宽度为7680，是否可以修改得到呢？期待您的回复。

**Comment by WangXuan95** [comment]
你好，资源量我恐怕是没有时间帮你优化了，你可以考虑自己优化。

不过你可以试试直接输入 width=7680 的照片进去，可能是支持的。我写的我只支持 宽度<4000 的照片，是因为我只充分验证了 宽度<4000 的照片。

**Comment by jzm1241** [comment]
好的  感谢您的回复，我这边在自己看看吧。
